env:
  CIRRUS_CLONE_DEPTH: 3

task:
  container:
    matrix:
      - image: ubuntu:18.04 # PHP 7.2
      - image: ubuntu:20.04 # PHP 7.4
      - image: ubuntu:22.04 # PHP 8.1
    cpu: 1
    memory: 512M
  env:
    DEBIAN_FRONTEND: noninteractive
  script:
    - apt-get -qy update >/dev/null
    - apt-get -qy install php-cli >/dev/null
    - php --version
    - ./test_ci.sh
